apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/export/web-storage-ge
    server: services.lab.example.com
  persistentVolumeReclaimPolicy: Recycle
